// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCXqcIetK2Eo19_054spdSrg7Th_TINnA',
    appId: '1:690849351051:web:bc205bd1dfe56f059f1b8e',
    messagingSenderId: '690849351051',
    projectId: 'login-ui-pers',
    authDomain: 'login-ui-pers.firebaseapp.com',
    storageBucket: 'login-ui-pers.appspot.com',
    measurementId: 'G-Y3LMYBTY0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5xgEGiKwiRSPnLoRR9KC6wnXEXpS6jN0',
    appId: '1:690849351051:android:7270b9d3ce6135b49f1b8e',
    messagingSenderId: '690849351051',
    projectId: 'login-ui-pers',
    storageBucket: 'login-ui-pers.appspot.com',
  );
}
